// What Bot Arena characters say in the news, by personality and moment.
// {b}: the other one (opponent, rival), {n}: a number (the streak).
// (Turkish lines keep names without suffixes: the right one depends on the name.)

export const QUOTE_SITS = ['streak', 'upset', 'upsetLoss', 'rival', 'champ', 'finalLoss', 'promoted', 'relegated', 'slump'];

export const QUOTES = {
  en: {
    cocky: {
      streak: ['{n} in a row. Somebody call me when it gets hard.', "Keep lining them up, I'll keep knocking them down."],
      upset: ['Underdog? I never read the odds.', '{b} was the favorite? Not anymore.'],
      upsetLoss: ['{b} got lucky. Write that down.', "One bad game. Don't get used to it."],
      rival: ['{b} keeps showing up. I keep winning.', "Rivalry? It's a one-way street."],
      champ: ['Told you all at the start of the season.', 'Make the trophy bigger next year.'],
      finalLoss: ['{b} won this time. This time.', "{b} can enjoy it. I'll be back for it."],
      promoted: ['Up a division. About time.', 'That division was too small for me anyway.'],
      relegated: ['A step back before the jump.', "Down? I'm just scouting the competition."],
      slump: ['Even legends take a nap.', "Relax. I'm letting them catch up."],
    },
    polite: {
      streak: ["{n} wins in a row, I'm very grateful to my opponents.", "A lucky run. I'll try to keep it going."],
      upset: ['Big respect to {b}, I just had a good day.', "I didn't expect that. Thank you all!"],
      upsetLoss: ['{b} played really well, well deserved.', "Congratulations to {b}. I'll learn from this."],
      rival: ['{b} always pushes me to be better.', 'Every game with {b} is a pleasure.'],
      champ: ['Thank you to everyone, what a season!', "I'm honored. Well played, everyone."],
      finalLoss: ['Congratulations {b}, you were the better player.', 'A great final. {b} earned it.'],
      promoted: ['Excited for the next division. Thank you!', "Moving up! I'll do my best."],
      relegated: ["Not my season. I'll work hard and come back.", 'A fair result. Next season will be better.'],
      slump: ["A rough patch. I'll keep practicing.", "Not my week, but I'm still learning."],
    },
    smug: {
      streak: ['{n} straight. I barely had to move.', 'They walk into my sights. Every time.'],
      upset: ['The numbers said {b}. The scoreboard said me.', 'Favorites are just targets with a reputation.'],
      upsetLoss: ["{b} won. I'll let them have this one.", 'Even the best angle has an off day.'],
      rival: ["{b} knows exactly where I'll be. Doesn't help.", 'Same spot, same result, {b}.'],
      champ: ['Champion. As expected.', "I didn't come here to make friends. I came for this."],
      finalLoss: ['{b} took the final. Enjoy the borrowed trophy.', 'Silver suits me. For now.'],
      promoted: ["Up a division. The view's better from here.", "I'll find a new favorite corner upstairs."],
      relegated: ['Down a division. More targets for me.', 'Interesting. The lower floor needs me.'],
      slump: ["A short break from winning. Don't get comfortable.", 'Even I let a few slide.'],
    },
    mysterious: {
      streak: ['{n} wins. The count means nothing.', 'They never see where it comes from.'],
      upset: ['{b} looked the wrong way.', "Shadows don't care about ratings."],
      upsetLoss: ["{b} found me. Next time they won't.", 'Some nights the dark is too bright.'],
      rival: ['{b} and I... an old story.', "{b} hears footsteps. They're mine."],
      champ: ['A crown, and no one saw me coming.', 'It was always going to end like this.'],
      finalLoss: ["This final was {b}'s. The next one won't be.", "I'll be one step behind you, {b}. Waiting."],
      promoted: ['Higher. Quieter.', 'A new floor of shadows.'],
      relegated: ['Down into the dark. Good.', 'Sometimes you sink to strike.'],
      slump: ['Losing is a disguise.', "Let them think I'm gone."],
    },
    hothead: {
      streak: ["{n} in a row and I'm still angry!", "Who's next? Line up!"],
      upset: ["Rated higher? Didn't help you, {b}!", "That's for everyone who doubted me!"],
      upsetLoss: ['That was NOT fair, {b}! Rematch!', 'My keyboard is broken. Rematch!'],
      rival: ["{b}! I've been waiting for this all week!", 'Beat you again, {b}. Felt great. Again!'],
      champ: ["CHAMPION! Who said I couldn't?!", 'I fought for every round of this!'],
      finalLoss: ['Not like this! {b}, see you next season!', 'I want that final back!'],
      promoted: ["Up! And I'm just getting warmed up!", 'Next division, watch out!'],
      relegated: ["Relegated?! I'll be back angrier.", "This is a mistake and I'll prove it!"],
      slump: ['Everything is lagging today!', "One more loss and I'm throwing the mouse."],
    },
    joker: {
      streak: ['{n} wins? I should buy a lottery ticket.', "My aim is on a winning streak. My jokes aren't."],
      upset: ['Plot twist! Sorry, {b}.', 'I was told this was a practice match.'],
      upsetLoss: ['{b} won? I demand a recount... of my bullets.', "I let {b} win. It's called being nice."],
      rival: ['{b} and me: like a cat and a laser pointer.', '{b} again? We should just share a flat.'],
      champ: ['Champion? Does the trophy come with snacks?', "I'd like to thank my mouse pad."],
      finalLoss: ["Second best! That's still on the podium, right?", '{b} won the final. I won the crowd.'],
      promoted: ['Moving up! Do they have better chairs up there?', 'Promoted. Nobody tell my old division I was joking.'],
      relegated: ['Going down? Please hold the elevator.', 'Relegated. Time for a comeback montage.'],
      slump: ["I'm not losing, I'm giving tutorials.", 'My crosshair went on holiday.'],
    },
    stoic: {
      streak: ['{n} wins. Next match.', 'Same routine. Same focus.'],
      upset: ['Ratings are a guess. The match is the answer.', '{b} is strong. Today I was stronger.'],
      upsetLoss: ['{b} was better today. Noted.', 'A loss. Back to work.'],
      rival: ['{b} is a fine opponent.', 'Another meeting with {b}. Another lesson.'],
      champ: ['The work paid off.', 'Champion. Tomorrow we train.'],
      finalLoss: ['{b} deserved the final.', 'Second. We continue.'],
      promoted: ['Promoted. The work continues.', 'A new division. The same discipline.'],
      relegated: ['Relegated. We rebuild.', 'Accept it. Improve.'],
      slump: ['Losses happen. Stay calm.', 'A bad run ends with patience.'],
    },
    nervous: {
      streak: ["{n} in a row? Please don't jinx it...", "I'm scared to look at the scoreboard."],
      upset: ['Did I really beat {b}? Are you sure?', 'My hands are still shaking!'],
      upsetLoss: ['Sorry everyone... {b} was too good.', "I knew I'd mess up. I always do."],
      rival: ['{b} again... okay, okay, I did it!', "I can't believe I beat {b} again!"],
      champ: ['Me? Champion? I need to sit down.', 'Is this real? Someone pinch me.'],
      finalLoss: ["{b} won the final, but I'm happy I got there.", 'I froze in the final. Sorry.'],
      promoted: ["Promoted?! Oh no, they're all better up there.", 'I hope I belong up there...'],
      relegated: ['Relegated... I knew it.', 'Maybe the lower division is more my speed.'],
      slump: ['I think everyone can see my mistakes.', 'Breathe. Just breathe.'],
    },
  },
  tr: {
    cocky: {
      streak: ['Üst üste {n}. Zorlaşınca haber verin.', 'Siz dizin, ben devireyim.'],
      upset: ['Favori mi? Ben oranlara bakmam.', '{b} favoriydi demek? Artık değil.'],
      upsetLoss: ['{b} şanslıydı. Not alın.', 'Tek kötü maç. Alışmayın.'],
      rival: ['{b} hep karşıma çıkıyor. Ben de hep kazanıyorum.', 'Rekabet mi? Tek yönlü bir yol bu.'],
      champ: ['Sezon başında söylemiştim.', 'Seneye kupayı daha büyük yapın.'],
      finalLoss: ['{b} bu sefer kazandı. Bu sefer.', '{b} tadını çıkarsın. Geri alacağım.'],
      promoted: ['Bir lig yukarı. Vakti gelmişti.', 'O lig bana zaten dar geliyordu.'],
      relegated: ['Sıçramadan önce bir adım geri.', 'Aşağı mı? Rakipleri keşfe çıktım.'],
      slump: ['Efsaneler de bazen kestirir.', 'Sakin olun. Yetişsinler diye bekliyorum.'],
    },
    polite: {
      streak: ['Üst üste {n} galibiyet, rakiplerime minnettarım.', 'Şanslı bir seri. Sürdürmeye çalışacağım.'],
      upset: ['{b}, büyük saygılar; sadece iyi bir günümdeydim.', 'Hiç beklemiyordum. Hepinize teşekkürler!'],
      upsetLoss: ['{b} çok iyi oynadı, hak etti.', 'Tebrikler {b}. Bundan ders çıkaracağım.'],
      rival: ['{b} beni hep daha iyi olmaya zorluyor.', '{b} ile her maç bir zevk.'],
      champ: ['Herkese teşekkürler, ne sezondu!', 'Onur duydum. Herkes çok iyi oynadı.'],
      finalLoss: ['Tebrikler {b}, daha iyi olan sendin.', 'Harika bir finaldi. {b} hak etti.'],
      promoted: ['Üst lig için heyecanlıyım. Teşekkürler!', 'Yükseliyoruz! Elimden geleni yapacağım.'],
      relegated: ['Benim sezonum değildi. Çalışıp döneceğim.', 'Adil bir sonuç. Gelecek sezon daha iyi olacak.'],
      slump: ['Zor bir dönem. Çalışmaya devam.', 'Benim haftam değil ama hâlâ öğreniyorum.'],
    },
    smug: {
      streak: ['Üst üste {n}. Neredeyse hiç kıpırdamadım.', 'Hepsi nişangâhıma yürüyor. Her seferinde.'],
      upset: ['Rakamlar {b} dedi. Skor tabelası beni.', 'Favoriler, ünü olan hedeflerdir.'],
      upsetLoss: ['{b} kazandı. Bu seferlik bırakıyorum.', 'En iyi açının da kötü günü olur.'],
      rival: ['{b} nerede olacağımı biliyor. İşe yaramıyor.', 'Aynı köşe, aynı sonuç, {b}.'],
      champ: ['Şampiyon. Beklendiği gibi.', 'Buraya arkadaş edinmeye değil, bunun için geldim.'],
      finalLoss: ['Finali {b} aldı. Ödünç kupanın tadını çıkarsın.', 'Gümüş bana yakışıyor. Şimdilik.'],
      promoted: ['Bir lig yukarı. Manzara buradan daha güzel.', 'Üst katta yeni bir köşe bulurum.'],
      relegated: ['Bir lig aşağı. Bana daha çok hedef.', 'İlginç. Alt katın bana ihtiyacı var.'],
      slump: ['Kazanmaya kısa bir ara. Rahatlamayın.', 'Ben bile arada birkaçını kaçırırım.'],
    },
    mysterious: {
      streak: ['{n} galibiyet. Sayının bir anlamı yok.', 'Nereden geldiğini hiç görmüyorlar.'],
      upset: ['{b} yanlış yöne baktı.', 'Gölgeler puanları umursamaz.'],
      upsetLoss: ['{b} beni buldu. Bir dahakine bulamayacak.', 'Bazı geceler karanlık fazla aydınlık.'],
      rival: ['{b} ve ben... eski bir hikâye.', '{b} ayak sesleri duyuyor. Benimkiler.'],
      champ: ['Bir taç ve kimse gelişimi görmedi.', 'Hep böyle bitecekti.'],
      finalLoss: ['Bu final {b} içindi. Bir sonraki olmayacak.', 'Hep bir adım arkanda olacağım, {b}. Bekleyerek.'],
      promoted: ['Daha yüksek. Daha sessiz.', 'Yeni bir gölge katı.'],
      relegated: ['Karanlığa doğru aşağı. Güzel.', 'Bazen vurmak için batmak gerekir.'],
      slump: ['Kaybetmek bir kılık.', 'Gittiğimi sansınlar.'],
    },
    hothead: {
      streak: ['Üst üste {n} ve hâlâ sinirliyim!', 'Sıradaki kim? Sıraya girin!'],
      upset: ['Puanın yüksekmiş? İşe yaramadı {b}!', 'Bu bana inanmayanlar için!'],
      upsetLoss: ['Bu adil DEĞİLDİ {b}! Rövanş!', 'Klavyem bozuk. Rövanş!'],
      rival: ['{b}! Bütün hafta bunu bekledim!', 'Yine kazandım {b}! Harikaydı. Bir daha!'],
      champ: ['ŞAMPİYON! Kim yapamaz demişti?!', 'Bunun her raundu için savaştım!'],
      finalLoss: ['Böyle olmaz! {b}, gelecek sezon görüşürüz!', 'O finali geri istiyorum!'],
      promoted: ['Yukarı! Daha yeni ısınıyorum!', 'Üst lig, kendine dikkat et!'],
      relegated: ['Küme düşmek mi?! Daha sinirli döneceğim.', 'Bu bir hata ve bunu kanıtlayacağım!'],
      slump: ['Bugün her şey kasıyor!', "Bir yenilgi daha ve mouse'u fırlatıyorum."],
    },
    joker: {
      streak: ['{n} galibiyet mi? Piyango bileti almalıyım.', 'Nişanım seride, esprilerim değil.'],
      upset: ['Beklenmedik son! Kusura bakma {b}.', 'Bana antrenman maçı demişlerdi.'],
      upsetLoss: ['{b} mi kazandı? Yeniden sayım istiyorum... mermilerimi.', 'Kazansın diye izin verdim. Buna nezaket denir.'],
      rival: ['{b} ve ben: kedi ve lazer gibi.', 'Yine mi {b}? Artık ev arkadaşı olalım.'],
      champ: ['Şampiyon mu? Kupanın yanında çerez var mı?', "Mouse pad'ime teşekkür etmek istiyorum."],
      finalLoss: ['İkinci en iyi! Bu da kürsü sayılır, değil mi?', 'Finali {b} kazandı. Kalabalığı ben.'],
      promoted: ['Yükseliyoruz! Yukarıdaki sandalyeler daha mı iyi?', 'Terfi ettim. Eski ligime şaka yaptığımı söylemeyin.'],
      relegated: ['Aşağı mı iniyoruz? Asansörü tutun lütfen.', 'Küme düştüm. Geri dönüş klibi zamanı.'],
      slump: ['Kaybetmiyorum, ders veriyorum.', 'Nişangâhım tatile çıktı.'],
    },
    stoic: {
      streak: ['{n} galibiyet. Sıradaki maç.', 'Aynı rutin. Aynı odak.'],
      upset: ['Puan bir tahmin. Cevabı maç verir.', '{b} güçlü. Bugün ben daha güçlüydüm.'],
      upsetLoss: ['Bugün {b} daha iyiydi. Not edildi.', 'Bir yenilgi. İşe dönüyoruz.'],
      rival: ['{b} iyi bir rakip.', '{b} ile bir karşılaşma daha. Bir ders daha.'],
      champ: ['Emek karşılığını verdi.', 'Şampiyon. Yarın antrenman var.'],
      finalLoss: ['{b} finali hak etti.', 'İkinci. Devam ediyoruz.'],
      promoted: ['Terfi. Çalışma sürüyor.', 'Yeni bir lig. Aynı disiplin.'],
      relegated: ['Küme düştük. Yeniden kuracağız.', 'Kabul et. Gelişmeye bak.'],
      slump: ['Yenilgi olur. Sakin kal.', 'Kötü seri sabırla biter.'],
    },
    nervous: {
      streak: ['Üst üste {n}? Lütfen nazar değdirmeyin...', 'Skor tabelasına bakmaya korkuyorum.'],
      upset: ['{b} karşısında gerçekten kazandım mı? Emin misiniz?', 'Ellerim hâlâ titriyor!'],
      upsetLoss: ['Herkesten özür dilerim... {b} çok iyiydi.', 'Batıracağımı biliyordum. Hep batırırım.'],
      rival: ['Yine {b}... tamam, tamam, yaptım!', '{b} karşısında yine kazandığıma inanamıyorum!'],
      champ: ['Ben mi? Şampiyon mu? Oturmam lazım.', 'Bu gerçek mi? Biri beni çimdiklesin.'],
      finalLoss: ['Finali {b} kazandı ama oraya çıktığım için mutluyum.', 'Finalde dondum kaldım. Özür dilerim.'],
      promoted: ['Terfi mi?! Eyvah, yukarıdakiler hep daha iyi.', 'Umarım oraya aitimdir...'],
      relegated: ['Küme düştüm... biliyordum.', 'Belki alt lig bana daha uygundur.'],
      slump: ['Sanırım herkes hatalarımı görüyor.', 'Nefes al. Sadece nefes al.'],
    },
  },
};

export function quoteText(lang, q) {
  const pool = (QUOTES[lang] || QUOTES.en)[q.p]?.[q.sit] || QUOTES.en[q.p]?.[q.sit];
  if (!pool) return '';
  return pool[q.i % pool.length].replace(/\{b\}/g, q.b || '').replace(/\{n\}/g, q.n ?? '');
}
